version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backendReactShop/Dockerfile
    container_name: reactshop-backend
    ports:
      - '3000:3000'
    env_file:
      - backendReactShop/.env.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - reactshop-network

  frontend:
    build:
      context: .
      dockerfile: frontendReactShop/Dockerfile
    container_name: reactshop-frontend
    ports:
      - '80:80'
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - reactshop-network

networks:
  reactshop-network:
    driver: bridge
