version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backendReactShop/Dockerfile
    container_name: reactshop-backend
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - reactshop-network

  frontend:
    build:
      context: .
      dockerfile: frontendReactShop/Dockerfile
    container_name: reactshop-frontend
    network_mode: host
    depends_on:
      - backend
    restart: unless-stopped

networks:
  reactshop-network:
    driver: bridge
