version: '3.8'

services:
  backend:
    build:
      context: ./backendReactShop
      dockerfile: Dockerfile
    container_name: reactshop-backend
    restart: unless-stopped
    networks:
      - reactshop-network

  frontend:
    build:
      context: ./frontendReactShop
      dockerfile: Dockerfile
    container_name: reactshop-frontend
    restart: unless-stopped
    networks:
      - reactshop-network

  nginx:
    image: nginx:stable
    container_name: reactshop-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - reactshop-network

networks:
  reactshop-network:
    driver: bridge
